## Both functions work in conjunction, the first creates an object, this case a Matrix, 
## that also has its inverse. So makeCacheMatrix has a matrix (x) and its inverse (inv) in it
## creating an "Environment" that stores this variables.

## Write a short comment describing this function

makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        
        set <- function(y){
          x <<- y
          inv <<- NULL
        }
        get <- function() x
        setinv <- function(solve ) inv <<- solve
        getinv <- function() inv
        list(set= set, get= get, setinv= setinv, getinv= getinv)

}


## CacheSolve evaluates the object generated by makeCacheMatrix and returns the inverse of the Matrix if it was priviously genereated or if not it calculates and the it assigna

cacheSolve <- function(x, ...) {
        inv <- x$getinv()
        if(!is.null(inv)){
          message("getting cache data")
          return(inv)
        }
  
        data <- x$get()
        inv <- solve(data, ...)
        x$setinv(inv)
        inv
  
}
## Return a matrix that is the inverse of 'x'
